### ISSUE TITLE
makeFields duplicate typeclass avoidance breaks in combined TH splice

### ISSUE THREAD

**Issue by anderspapitto** [ekmett/lens#686] opened 2016-11-12 02:48 UTC
this works

```
makeFields ''Bar
makeFields ''Foo
```

while this doesn't

```
liftM concat $ mapM makeFields [ ''Bar, ''Foo ]
```

if Bar and Foo are defined as

```
data Bar = Bar { barSomething :: Int }
data Foo = Foo { fooSomething :: Int }
```

with an error about the `HasSomething` typeclass already existing.

why would I ever want to do the `mapM makeFields` thing? TH is slow with ghcjs, and that only counts as one TH invocation, instead of 2. So it's linearly faster to compile in the number of datatypes I have.

**Comment by RyanGlScott** [comment] 2016-11-14 14:20
This is essentially a duplicate of #643, so I'll close this in favor of that issue.

**Comment by neongreen** [comment] 2016-11-14 14:28
@RyanGlScott I'm not sure it's a duplicate of #643. In that issue, `declareFields` has knowledge of what it generates, and can take it into account; in this issue, each call to `makeFields` is separate and I'm not sure it's even possible for one of those calls to know what the other call has generated. Unless I'm mistaken, a fix for #643 won't solve this issue.

On the other hand, I assume that @anderspapitto doesn't actually care about how lenses generated, so if `declareFields` works it might be fine for them. (Or it might be not, if they also want to retain the original accessors or if their types are declared in different modules, etc.)

**Comment by RyanGlScott** [comment] 2016-11-14 14:33
@neongreen, fair point. I'll leave this open so that if we do come up with a fix for either issue, we can evaluate how well it works for each use case.

**Comment by glguy** [comment] 2017-01-29 03:28
It's not going to be possible for the later invocation of makeFields to know what code the earlier one generated. It's necessary to separate these into two top-level calls to makeFields, or to use declareFields

**Closed by glguy** 2017-01-29 03:28 UTC
