### ISSUE TITLE
Error with kinds on GHC 8 RC

### ISSUE THREAD

**Issue by Heather** [ekmett/lens#626] opened 2016-01-15 12:52 UTC
```
src\Control\Lens\Type.hs:447:1: error:
    * Kind variable `k3' is implicitly bound in datatype
      `Equality', but does not appear as the kind of any
      of its type variables. Perhaps you meant
      to bind it (with TypeInType) explicitly somewhere?
      Type variables with inferred kinds:
        (s :: k1) (t :: k2) (a :: k1) (b :: k2)
    * In the type declaration for `Equality'
cabal: Error: some packages failed to install:
lens-4.13.1 failed during the building phase. The exception was:
ExitFailure 1
```

possible workaround

``` haskell
-- Note: Composition with an 'Equality' is index-preserving.
#if __GLASGOW_HASKELL__ >= 800
type Equality (s :: k1) (t :: k2) (a :: k1) (b :: k2) = forall (p :: k1 -> * -> *) (f :: k2 -> *) . p a (f b) -> p s (f t)
#elif __GLASGOW_HASKELL__ >= 708
type Equality (s :: k1) (t :: k2) (a :: k1) (b :: k2) = forall (p :: k1 -> k3 -> *) (f :: k2 -> k3) . p a (f b) -> p s (f t)
#elif __GLASGOW_HASKELL__ >= 706
type Equality (s :: k1) (t :: k2) (a :: k1) (b :: k2) = forall (p :: k1 -> * -> *) (f :: k2 -> *) . p a (f b) -> p s (f t)
#else
type Equality s t a b = forall p (f :: * -> *) . p a (f b) -> p s (f t)
#endif
```

maybe it's GHC bug, not sure...

then when bug will be fixed we can add

``` haskell
if __GLASGOW_HASKELL__ >= 801
type Equality (s :: k1) (t :: k2) (a :: k1) (b :: k2) = forall (p :: k1 -> k3 -> *) (f :: k2 -> k3) . p a (f b) -> p s (f t)
```

... what do you think?

**Comment by RyanGlScott** [comment] 2016-01-15 15:31
Yikes! I'm reasonably certain this is a GHC bug of some kind (pun intended), since the error message mentions datatypes, but this is a type synonym!

@goldfirere, does this look fishy, or is this an example of code which shouldn't have type-checked before? Here's a standalone, reproducible example:

```haskell
{-# LANGUAGE RankNTypes, PolyKinds, KindSignatures #-}
module Equality where

type Equality (s :: k1) (t :: k2) (a :: k1) (b :: k2) = forall (p :: k1 -> k3 -> *) (f :: k2 -> k3) . p a (f b) -> p s (f t)
```

**Comment by goldfirere** [comment] 2016-01-15 16:35
That definition is indeed bogus and should not have been admitted previously. (The error message should be tweaked not to discuss `datatype`, though.) Try writing it out with all kind parameters explicit. Where does `k3` belong? It's entirely unclear. If it's on the left, it can't be inferred from the other type parameters. Perhaps you meant it to be bound by the `forall`. GHC 8 has simplified implicit quantification, with one effect being that kind variables are now not quantified where sometimes they were previously. So just include `k3` in the forall.

**Comment by RyanGlScott** [comment] 2016-01-15 16:51
Thank makes perfect sense. Thanks!

GHCi also confirms this explanation: if you let kind inference take over, you can see pretty easily how bogus this is:

```haskell
$ /opt/ghc/head/bin/ghci -XPolyKinds -XRankNTypes
GHCi, version 8.1.20160113: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/xnux/.ghci
λ> type Equality s t a b = forall p f. p a (f b) -> p s (f t)
λ> :i Equality 
type Equality (s :: k) (t :: k1) (a :: k) (b :: k1) =
  forall (p :: k -> GHC.Prim.Any -> *) (f :: k1 -> GHC.Prim.Any).
  p a (f b) -> p s (f t)
```

That is a bit unsettling, so I think the best course of action is to redefine `Equality` as follows:

```haskell
#if __GLASGOW_HASKELL__ >= 800
{-# LANGUAGE TypeInType #-}
#endif

#if __GLASGOW_HASKELL__ >= 800
type Equality (s :: k1) (t :: k2) (a :: k1) (b :: k2) = forall k3 (p :: k1 -> k3 -> *) (f :: k2 -> k3) .
#elif __GLASGOW_HASKELL__ >= 706
type Equality (s :: k1) (t :: k2) (a :: k1) (b :: k2) = forall (p :: k1 -> * -> *) (f :: k2 -> *) .
#else
type Equality s t a b = forall p (f :: * -> *) .
#endif
    p a (f b) -> p s (f t)
```

@treeowl, you originally wrote this definition. Do you rely on the GHC 7.8–specific kind behavior for anything?

**Comment by treeowl** [comment] 2016-01-18 06:51
@RyanGlScott, the expression you now have for `__GLASGOW_HASKELL__ >= 800` is indeed what I was aiming for in `708`. It seemed to work for my test cases, so I didn't realize anything shady was happening! I'm perfectly okay being conservative with `708`. @goldfirere, quick question: will there be any issues producing *values* of type `Equality s t a b` in modules that don't use language extensions?

**Comment by treeowl** [comment] 2016-01-18 06:53
@goldfirere speaking of things, can your brand-new kind equality improve things any for `800`? Avoiding the matching-kinds assumption would add an extra layer of coolness here, I think.

**Comment by goldfirere** [comment] 2016-01-18 12:55
I believe that the definitions under 708 and under 800 are equivalent -- if I understand correctly, the interpretation under 708 of that `forall` binds the kind variable, too. It's just that implicit quantification of kinds changes in 800, but 800 also gives you the ability to control it directly.

As for improvements, I can't say. I don't know lens well enough (at all?) to be able to opine. Sorry!

**Comment by treeowl** [comment] 2016-01-18 13:40
The idea of the quantified k3 is to make Equality s t a b a bit stronger,
so they can express substitution more generally. This goes beyond anything
lensy, per se.

**Comment by goldfirere** [comment] 2016-01-18 13:47
Yes, well, I mean I have no clue what `s`, `t`, `a`, or `b` are in lensy things. Maybe that idea goes beyond lens. But then I know even less than I thought. :)

**Comment by RyanGlScott** [comment] 2016-01-18 15:32
@treeowl: What do you mean by "matching-kinds assumption"?

**Comment by byorgey** [comment] 2016-01-18 16:33
@goldfirere `s` is the type of the whole, and `a` is the type of the subthing(s) focused on by the lensy thing.  `t` and `b` are similar, and allow you to have type-changing lenses, *i.e.* by changing the `a` subpart(s) into `b`s you can change the entire `s` into a `t`.

Of course, `Equality` is a special case where everything actually has to be the same, but that's the general idea.

**Comment by treeowl** [comment] 2016-01-18 16:45
(Equality s t a b) is a witness that s~a and t~b, actually.

Equality s t a b = forall f p . p a (f b) -> p s (f t)

It's so general that it can only be satisfied under these conditions.

We currently assume that a and a have the same kind, and that t and b have
the same kind. I'm curious whether Richard's recent work would allow us to
drop that assumption.

**Comment by glguy** [comment] 2016-02-08 16:45
@RyanGlScott Can we close this now that 320cdb3125f0e5b9d79f1421ab9e28d3c95929eb is committed and `kan-extensions-5.0.1` is released?

**Comment by RyanGlScott** [comment] 2016-02-08 16:51
Sure. If folks still want to discuss the kind of `Equality`, that is probably best left to a separate GitHub issue, since this one is just about the (now-fixed) compilation error.

**Closed by RyanGlScott** 2016-02-08 16:51 UTC
