### ISSUE TITLE
declareFields can generate duplicate Has* classes

### ISSUE THREAD

**Issue by aavogt** [ekmett/lens#643] opened 2016-04-05 21:22 UTC
``` haskell
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE FunctionalDependencies #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE TemplateHaskell #-}
import Control.Lens

declareFields [d|
  data A = A { aA :: Int }
  data B = B { bA :: Int }
 |]
```

Two `class HasA s a` are generated. Separate calls to makeFields / declareFields for each data type don't run into this problem. Using lens-4.13.2.1.

**Comment by RyanGlScott** [comment] 2016-04-07 13:47
The explanation for why this bug occurs is pretty simple: the [underlying TH machinery](https://github.com/ekmett/lens/blob/bdb7e9142e83ff92a3f914a7ffc7ea4f5582a6d9/src/Control/Lens/Internal/FieldTH.hs#L284) uses the `lookupTypeName` function to determine whether a given `Has*` class is already defined. The problem is that `lookupTypeName` [only knows about the context](http://hackage.haskell.org/package/template-haskell-2.10.0.0/docs/Language-Haskell-TH-Syntax.html#namelookup) of the outermost `$(...)` splice being run, so `lookupTypeName` won't realize that another `HasA` class is *about* to be spliced.

As for a fix, I'm not sure. I suppose we could accumulate a list of `Name`s that are about to be spliced, and consult that list as well to see if `HasA` already exists. Thoughts, @glguy?

**Comment by RyanGlScott** [comment] 2016-11-14 14:34
@anderspapitto has a very similar problem in #686. If we come up with a fix for this, we should also make sure to examine #686 more closely as well.

**Closed** 2017-06-20 22:35 UTC
Labels: bug, in progress, template-haskell
