### ISSUE TITLE
cabal installation of lens-4.17 in Windows fails on GHC-7.10.3

### ISSUE THREAD

**Issue by sbutsky** [ekmett/lens#840] opened 2019-04-03 16:19 UTC
With following compilation error:

```
Resolving dependencies...
Starting     lens-4.17
Building     lens-4.17
Failed to install lens-4.17
Build log ( C:\Users\User\AppData\Roaming\cabal\logs\ghc-7.10.3\lens-4.17-J2putzcdfMqFPVnfRw0b4p.log ):
Building lens-4.17...
Preprocessing library lens-4.17...
[54 of 83] Compiling Paths_lens       ( dist\build\autogen\Paths_lens.hs, dist\build\Paths_lens.o )
[55 of 83] Compiling Control.Lens.Zoom ( src\Control\Lens\Zoom.hs, dist\build\Control\Lens\Zoom.o )

src\Control\Lens\Zoom.hs:195:10:
    Could not deduce (MonadState s (ExceptT e m))
      arising from the superclasses of an instance declaration
    from the context (Zoom m n s t)
      bound by the instance declaration
      at src\Control\Lens\Zoom.hs:195:10-61
    In the instance declaration for
      `Zoom (ExceptT e m) (ExceptT e n) s t'
cabal: Leaving directory '.'
cabal.exe: Error: some packages failed to install:
lens-4.17-J2putzcdfMqFPVnfRw0b4p failed during the building phase. The
exception was:
ExitFailure 1
```

**Comment by RyanGlScott** [comment] 2019-04-03 16:53
Curious, I'm not able to reproduce this. Can you include the full build log when you try installing with the `-v` flag? I'm interested to see what build plan is being used.

**Comment by sbutsky** [comment] 2019-04-03 17:06
Here it is. I guess not quite informative though

creating dist\setup
F:\Projects\Haskell\lens\dist\setup\setup.exe build --verbose=2
--builddir=dist --jobs=8
Component build order: library
creating dist\build
creating dist\build\autogen
Building lens-4.17...
"F:\PROGRA~1\HASKEL~1\7.10.3\bin\ghc-pkg.exe" "init" "dist\package.conf.inplace"
Preprocessing library lens-4.17...
Building library...
creating dist\build
"F:\PROGRA~1\HASKEL~1\7.10.3\bin\ghc.exe" "--make" "-fbuilding-cabal-package" "-O" "-j8" "-outputdir" "dist\build" "-odir" "dist\build" "-hidir" "dist\build" "-stubdir" "dist\build" "-i" "-idist\build" "-isrc" "-idist\build\autogen" "-Idist\build\autogen" "-Idist\build" "-Iinclude" "-IF:\Program Files\Haskell Platform\8.4.3\mingw\include" "-optP-traditional" "-optP-DTRUSTWORTHY=1" "-optP-DINLINING" "-optP-include" "-optPdist\build\autogen\cabal_macros.h" "-this-package-key" "lens_9Oplfgpx2R31VnSJeyHrvi" "-hide-all-packages" "-package-db" "dist\package.conf.inplace" "-package-id" "array-0.5.1.0-1e6afdd1db5c2d707efe995169e8d18a" "-package-id" "base-4.8.2.0-14035a44a8b95c6832da6dae1420f59e" "-package-id" "base-orphans-0.8-IGL8jDom0t0FuOFs8UjJ0n" "-package-id" "bifunctors-5.5.3-EY388tnDBqNDrzdqTsSfzJ" "-package-id" "bytestring-0.10.6.0-407442efd50495753f55535baadb535d" "-package-id" "call-stack-0.1.0-Bdy6qJeAGaaE9SlSnZB4Kx" "-package-id" "comonad-5.0.4-6hBL3yZqrcg9EtKhPUAn7F" "-package-id" "containers-0.5.6.2-1ea8e8860526df8088945a0426795249" "-package-id" "contravariant-1.5-Gf9ePjLl3a78GnpOZbna1o" "-package-id" "distributive-0.6-Eb3xPCRSUmy3d6Brj6Lfld" "-package-id" "exceptions-0.10.0-9z5oOO8cQvUC0wgmcz9NTN" "-package-id" "filepath-1.4.0.0-5ea0fbdbd701d44e39a27224fbae8f37" "-package-id" "free-5.1-EHWlegIBjzIBcpk2EhV0wN" "-package-id" "generic-deriving-1.12.3-GtoUxnYMtYNHONJhQcEVer" "-package-id" "ghc-prim-0.4.0.0-428c198583a031a3ea42dd32ae6f9bab" "-package-id" "hashable-1.2.7.0-EjHgeghzjiE7EuOmLKOnVg" "-package-id" "kan-extensions-5.2-6N3TTnA855tJGa7rrocmBQ" "-package-id" "mtl-2.1.2-5SXar3cxvFe31PTwpgxCXT" "-package-id" "parallel-3.2.2.0-5CASEZtJo8P2YnMNDEEFXo" "-package-id" "profunctors-5.3-6JmEYZOtmvAJSaAqAhLICe" "-package-id" "reflection-2.1.4-E4B55HaayVC3g9j44rHOHb" "-package-id" "semigroupoids-5.3.2-Ir5N04ycI7unyNKz8eAp9" "-package-id" "semigroups-0.18.5-LmAwjWYwydpEafUsxwlZOI" "-package-id" "tagged-0.8.6-ft9u3rcCtGDAa1URHJFak" "-package-id" "template-haskell-2.10.0.0-bcb07fec12f32563bb45d7fb009640b1" "-package-id" "text-1.2.3.1-IiNqaP896fV2csKOsCtr3O" "-package-id" "th-abstraction-0.2.11.0-5CUCWnK63L4DHmkRxSlVt4" "-package-id" "transformers-0.4.2.0-560c443a4c8f3854b85644b981ff03b6" "-package-id" "transformers-compat-0.6.2-F4VmvitSuXoASRTzxLpLTi" "-package-id" "unordered-containers-0.2.10.0-I3LIovSoK4y2iUfmrNGHuz" "-package-id" "vector-0.12.0.2-ZV2Run2Uhk2g0tsx6cFKF" "-XHaskell2010" "Control.Exception.Lens" "Control.Lens" "Control.Lens.At" "Control.Lens.Combinators" "Control.Lens.Cons" "Control.Lens.Each" "Control.Lens.Empty" "Control.Lens.Equality" "Control.Lens.Extras" "Control.Lens.Fold" "Control.Lens.Getter" "Control.Lens.Indexed" "Control.Lens.Internal" "Control.Lens.Internal.Bazaar" "Control.Lens.Internal.ByteString" "Control.Lens.Internal.Coerce" "Control.Lens.Internal.Context" "Control.Lens.Internal.CTypes" "Control.Lens.Internal.Deque" "Control.Lens.Internal.Exception" "Control.Lens.Internal.FieldTH" "Control.Lens.Internal.PrismTH" "Control.Lens.Internal.Fold" "Control.Lens.Internal.Getter" "Control.Lens.Internal.Indexed" "Control.Lens.Internal.Instances" "Control.Lens.Internal.Iso" "Control.Lens.Internal.Level" "Control.Lens.Internal.List" "Control.Lens.Internal.Magma" "Control.Lens.Internal.Prism" "Control.Lens.Internal.Review" "Control.Lens.Internal.Setter" "Control.Lens.Internal.TH" "Control.Lens.Internal.Zoom" "Control.Lens.Iso" "Control.Lens.Lens" "Control.Lens.Level" "Control.Lens.Operators" "Control.Lens.Plated" "Control.Lens.Prism" "Control.Lens.Reified" "Control.Lens.Review" "Control.Lens.Setter" "Control.Lens.TH" "Control.Lens.Traversal" "Control.Lens.Tuple" "Control.Lens.Type" "Control.Lens.Unsound" "Control.Lens.Wrapped" "Control.Lens.Zoom" "Control.Monad.Error.Lens" "Control.Parallel.Strategies.Lens" "Control.Seq.Lens" "Data.Array.Lens" "Data.Bits.Lens" "Data.ByteString.Lens" "Data.ByteString.Strict.Lens" "Data.ByteString.Lazy.Lens" "Data.Complex.Lens" "Data.Data.Lens" "Data.Dynamic.Lens" "Data.HashSet.Lens" "Data.IntSet.Lens" "Data.List.Lens" "Data.Map.Lens" "Data.Sequence.Lens" "Data.Set.Lens" "Data.Text.Lens" "Data.Text.Strict.Lens" "Data.Text.Lazy.Lens" "Data.Tree.Lens" "Data.Typeable.Lens" "Data.Vector.Lens" "Data.Vector.Generic.Lens" "GHC.Generics.Lens" "System.Exit.Lens" "System.FilePath.Lens" "System.IO.Error.Lens" "Language.Haskell.TH.Lens" "Numeric.Lens" "Numeric.Natural.Lens" "Paths_lens" "-Wall" "-fwarn-tabs" "-O2" "-fdicts-cheap" "-funbox-strict-fields" "-fmax-simplifier-iterations=10"
[55 of 83] Compiling Control.Lens.Zoom ( src\Control\Lens\Zoom.hs, dist\build\Control\Lens\Zoom.o )

**Comment by RyanGlScott** [comment] 2019-04-03 17:58
Hm, something is rather strange about that build plan. It's trying to combine `mtl-2.1.2` with `transformers-0.4.2.0`, but according to the [Hackage page for `mtl-2.1.2`](http://hackage.haskell.org/package/mtl-2.1.2), it should only be buildable with `transformers==0.3.*`.

How are you invoking `cabal`?

**Comment by sbutsky** [comment] 2019-04-03 18:17
I've downloaded via cabal get lens-4.17 then cabal configure then build

**Comment by RyanGlScott** [comment] 2019-04-03 18:24
I'm afraid that I don't know how you installed your dependencies, then. If I try to install build `lens-4.17` with GHC 7.10.3 and `mtl-2.1.2`, it fails very early on for me:

```
$ cabal v1-install -w /opt/ghc/7.10.3/bin/ghc --constraint="mtl==2.1.2" --only-dep
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: lens-4.17 (user goal)
[__1] trying: transformers-compat-0.6.4 (dependency of lens)
[__2] trying: transformers-0.4.2.0/installed-814... (dependency of lens)
[__3] next goal: mtl (dependency of lens)
[__3] rejecting: mtl-2.2.2, mtl-2.2.1, mtl-2.2.0.1, mtl-2.2, mtl-2.1.3.1
(constraint from command line flag requires ==2.1.2)
[__3] rejecting: mtl-2.1.2 (conflict: transformers==0.4.2.0/installed-814...,
mtl => transformers==0.3.*)
[__3] rejecting: mtl-2.1.1, mtl-2.1, mtl-2.0.1.1, mtl-2.0.1.0, mtl-2.0.0.0,
mtl-1.1.1.1, mtl-1.1.1.0, mtl-1.1.0.2, mtl-1.1.0.1, mtl-1.1.0.0, mtl-1.0
(constraint from command line flag requires ==2.1.2)
[__3] fail (backjumping, conflict set: lens, mtl, transformers)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: mtl, transformers, lens,
transformers-compat, base
```

As you can see in the error message, it complains that `mtl-2.1.2` cannot be built together with `transformers-0.4.2.0`.

**Comment by RyanGlScott** [comment] 2019-04-11 13:24
At this point, I think the only thing we can do is diagnose why `cabal` is choosing an unsupported build plan. Some useful questions to answer are:

* What version of `cabal` are you using?
* How did you obtain your copy of `cabal`? (e.g., your system's package manager? The Haskell Platform? Something else?)
* How did you install your dependencies? (e.g., `cabal install`? Your system's package manager? The Haskell Platform? Something else?)
* What are the exact steps you're using to configure and build `lens-4.17`?
* Are you passing any special flags to `cabal` (e.g., `--allow-newer`)?
* Do you have any special configuration in your `~/.cabal/config` file?
* Do you experience the same error if you try to build `lens-4.17` with `cabal new-build`?

**Comment by RyanGlScott** [comment] 2023-12-09 15:26
Closing as `lens` no longer supports building with GHC 7.10.

**Closed by RyanGlScott** 2023-12-09 15:26 UTC
Labels: build-system, can't duplicate
