### ISSUE TITLE
Some classes in their own package

### ISSUE THREAD

**Issue by tonymorris** [ekmett/lens#526] opened 2015-02-17 04:10 UTC
I am currently toying with the idea of making libraries not depend on the `lens` package, but instead, depend on smaller packages like `profunctor`.

This means I must also forgo type-class instances e.g. `Swapped` and `Reversing` from `Control.Lens.Iso`. Perhaps these type-classes can go in their own package? Is there an appropriate way of lessening the dependency on `lens` while achieving the benefits of things like `Swapped`?

**Comment by ekmett** [comment] 2015-02-17 04:13
`lens` has a dozen of these little classes.

`Swapped` is pretty small, and has no weird instances to worry about.

`Reversing` would have a bunch of dependencies. `vector`, `text`, `bytestring`, etc.

But whenever this comes up, folks inevitably want all the `FunctorWithIndex`, `FoldableWithIndex`, `TraversableWithIndex`, `Each`, `Ixed`, `At`...

By the time you get done sliding down the slippery slope with that we get right back where we are with dependencies and its even harder for us to work.

**Comment by bennofs** [comment] 2015-02-17 11:08
For `Swapped`, could that be moved to `bifunctors`? That would at least solve this issue.

**Comment by bennofs** [comment] 2015-02-17 11:10
Ah, the issue is probably that this would add a `profunctors` dependency to `bifunctors`

**Comment by ekmett** [comment] 2015-07-08 20:27
I'm going to close this as I just don't see this happening at this point.

**Closed by ekmett** 2015-07-08 20:27 UTC
